//! Fixup: strip SubgraphAdditiveRace (SADD) from creature Race records.
//!

//!
//! # What this does
//! For creature conversions (NPC_/LVLN root), the converter emits full-clone Race
//! records.  The FO76 `SubgraphAdditiveRace` value is meaningless in FO4 creature
//! races (the Race owns its complete Subgraphs directly) and the blind FK remap
//! often produces a dangling reference.  This fixup strips the SADD subrecord
//! from every RACE record in the target plugin.
//!
//! Weapon/armor additive races are unaffected — they are generated by
//! `_generate_additive_races` and receive a correct SubgraphAdditiveRace.
//!
//! # SADD subrecord
//! `RACE.SADD` — a 4-byte FormID pointing at another Race used for additive
//! subgraph blending.  We remove every SADD subrecord found.

use crate::fixups::creature::{
    creature_internal_fixup_applies, race_internal_fixup_applies_to_record,
};
use crate::fixups::{Fixup, FixupConfig, FixupContext, FixupError, FixupReport};
use crate::formkey_mapper::FormKeyMapper;
use crate::full_plugin::FixupScope;
use crate::ids::{SigCode, SubrecordSig};
use crate::record::{FieldEntry, Record};
use crate::session::PluginSession;
use crate::sym::StringInterner;

// ---------------------------------------------------------------------------
// Public fixup struct
// ---------------------------------------------------------------------------

pub struct StripCreatureSubgraphAdditiveRaceFixup;

impl Fixup for StripCreatureSubgraphAdditiveRaceFixup {
    fn name(&self) -> &'static str {
        "strip_creature_subgraph_additive_race"
    }

    fn scope(&self) -> FixupScope {
        // Whole-plugin: self-gates per RACE on the creature keyword below.
        FixupScope::CreatureGated
    }

    fn uses_session(&self) -> bool {
        true
    }

    fn applies_to(&self, ctx: &FixupContext) -> bool {
        creature_internal_fixup_applies(ctx.config)
    }

    fn applies_to_session(&self, _session: &PluginSession, config: &FixupConfig) -> bool {
        creature_internal_fixup_applies(config)
    }

    fn run_with_session(
        &self,
        session: &mut PluginSession,
        mapper: &mut FormKeyMapper,
        config: &FixupConfig,
    ) -> Result<FixupReport, FixupError> {
        let race_sig =
            SigCode::from_str("RACE").map_err(|e| FixupError::SchemaError(e.to_string()))?;
        let target_schema = config
            .target_schema
            .as_deref()
            .ok_or_else(|| FixupError::Other("missing target schema in fixup config".into()))?;

        let mut report = FixupReport::empty();
        let race_fks = session
            .form_keys_of_sig(race_sig, mapper.interner)
            .map_err(|e| FixupError::HandleError(e.to_string()))?;

        for fk in race_fks {
            let mut record = match session.record_decoded(&fk, target_schema, mapper.interner) {
                Ok(r) => r,
                Err(e) => {
                    let w = mapper.interner.intern(&format!("strip_sadd_read:{e}"));
                    report.warnings.push(w);
                    continue;
                }
            };

            // Per-record gate (whole-plugin only): skip confirmed humanoid
            // (ActorTypeNPC) races and generated additive races so a valid
            // SubgraphAdditiveRace on weapon/armor/human/super-mutant races
            // survives. Robots / segmented-creature races still get their
            // dangling FO76 SADD stripped. No-op on a creature-graph walk
            // (every race in scope is creature-relevant).
            if !race_internal_fixup_applies_to_record(&record, config, mapper.interner) {
                continue;
            }

            let dropped = apply_to_record(&mut record, mapper.interner);
            if dropped > 0 {
                session
                    .replace_record(record, target_schema, mapper.interner)
                    .map_err(|e| FixupError::HandleError(e.to_string()))?;
                report.records_changed += 1;
                report.records_dropped += dropped;
            }
        }

        Ok(report)
    }
}

// ---------------------------------------------------------------------------
// Record-level mutation (extracted for unit-test access)
// ---------------------------------------------------------------------------

/// Strip all SADD subrecords from `record`.
///
/// Returns the count of SADD entries removed.
pub fn apply_to_record(record: &mut Record, interner: &StringInterner) -> u32 {
    if preserves_source_additive_race(record, interner) {
        return 0;
    }

    let sadd_sig = match SubrecordSig::from_str("SADD") {
        Ok(s) => s,
        Err(_) => return 0,
    };

    let before = record.fields.len();
    let mut kept: smallvec::SmallVec<[FieldEntry; 8]> = smallvec::SmallVec::new();
    for entry in record.fields.drain(..) {
        if entry.sig != sadd_sig {
            kept.push(entry);
        }
    }
    record.fields = kept;

    (before - record.fields.len()) as u32
}

fn preserves_source_additive_race(record: &Record, interner: &StringInterner) -> bool {
    record_editor_id(record, interner)
        .map(|eid| eid.eq_ignore_ascii_case("OguaRace"))
        .unwrap_or(false)
}

fn record_editor_id<'a>(record: &'a Record, interner: &'a StringInterner) -> Option<&'a str> {
    if let Some(eid) = record.eid.and_then(|sym| interner.resolve(sym)) {
        return Some(eid);
    }

    let edid_sig = SubrecordSig::from_str("EDID").ok()?;
    record
        .fields
        .iter()
        .find(|entry| entry.sig == edid_sig)
        .and_then(|entry| match entry.value {
            crate::record::FieldValue::String(sym) => interner.resolve(sym),
            _ => None,
        })
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fixups::{FixupConfig, FixupContext};
    use crate::formkey_mapper::{FormKeyMapper, MapperOptions};
    use crate::ids::{FormKey, SigCode, SubrecordSig};
    use crate::record::{FieldEntry, FieldValue, Record, RecordFlags};
    use crate::schema::AuthoringSchema;
    use crate::sym::StringInterner;
    use std::sync::Arc;

    fn make_race_with_sadd(
        local: u32,
        plugin: &str,
        sadd_raw_id: Option<u32>,
        interner: &StringInterner,
    ) -> Record {
        let sig = SigCode::from_str("RACE").unwrap();
        let fk = FormKey {
            local,
            plugin: interner.intern(plugin),
        };
        let mut fields: smallvec::SmallVec<[FieldEntry; 8]> = smallvec::SmallVec::new();

        // Add EDID for well-formedness.
        let edid_sig = SubrecordSig::from_str("EDID").unwrap();
        let edid_sym = interner.intern("TestRace");
        fields.push(FieldEntry {
            sig: edid_sig,
            value: FieldValue::String(edid_sym),
        });

        if let Some(raw_id) = sadd_raw_id {
            let sadd_sig = SubrecordSig::from_str("SADD").unwrap();
            let mut payload: smallvec::SmallVec<[u8; 32]> = smallvec::SmallVec::new();
            payload.extend_from_slice(&raw_id.to_le_bytes());
            fields.push(FieldEntry {
                sig: sadd_sig,
                value: FieldValue::Bytes(payload),
            });
        }

        Record {
            sig,
            form_key: fk,
            eid: None,
            flags: RecordFlags::empty(),
            fields,
            warnings: smallvec::SmallVec::new(),
        }
    }

    #[test]
    fn strip_sadd_no_op_when_absent() {
        let mut interner = StringInterner::new();
        let mut record = make_race_with_sadd(0x000100, "Output.esp", None, &mut interner);
        let dropped = apply_to_record(&mut record, &interner);
        assert_eq!(dropped, 0);
    }

    #[test]
    fn strip_sadd_removes_entry() {
        let mut interner = StringInterner::new();
        let mut record =
            make_race_with_sadd(0x000100, "Output.esp", Some(0x00_ABCDEF), &mut interner);
        assert_eq!(record.fields.len(), 2); // EDID + SADD
        let dropped = apply_to_record(&mut record, &interner);
        assert_eq!(dropped, 1);
        let sadd_sig = SubrecordSig::from_str("SADD").unwrap();
        assert!(
            record.fields.iter().all(|e| e.sig != sadd_sig),
            "SADD must be gone"
        );
        // EDID must survive.
        let edid_sig = SubrecordSig::from_str("EDID").unwrap();
        assert!(record.fields.iter().any(|e| e.sig == edid_sig));
    }

    #[test]
    fn strip_sadd_preserves_ogua_additive_race() {
        let mut interner = StringInterner::new();
        let mut record =
            make_race_with_sadd(0x000100, "Output.esp", Some(0x00_ABCDEF), &mut interner);
        record.eid = Some(interner.intern("OguaRace"));

        let dropped = apply_to_record(&mut record, &interner);

        assert_eq!(dropped, 0);
        let sadd_sig = SubrecordSig::from_str("SADD").unwrap();
        assert!(record.fields.iter().any(|e| e.sig == sadd_sig));
    }

    #[test]
    fn applies_to_false_for_weap_root() {
        let schema = Arc::new(AuthoringSchema::for_game("fo4").unwrap());
        let mut ctx_interner = StringInterner::new();
        let mut mapper_interner = StringInterner::new();
        let config = FixupConfig {
            root_sig: Some(SigCode::from_str("WEAP").unwrap()),
            ..Default::default()
        };
        let mut mapper = FormKeyMapper::new([], MapperOptions::default(), &mut mapper_interner);
        let ctx = FixupContext {
            source_handle_id: 1,
            target_handle_id: 2,
            schema_target: &schema,
            schema_source: &schema,
            skip_record_sigs: crate::fixups::empty_skip_record_sigs(),
            mod_path: None,
            source_extracted_dir: None,
            target_master_handle_ids: &[],
            config: &config,
        };
        assert!(!StripCreatureSubgraphAdditiveRaceFixup.applies_to(&ctx));
        let _ = mapper;
    }

    #[test]
    fn applies_to_true_for_npc_root() {
        let schema = Arc::new(AuthoringSchema::for_game("fo4").unwrap());
        let mut ctx_interner = StringInterner::new();
        let mut mapper_interner = StringInterner::new();
        let config = FixupConfig {
            root_sig: Some(SigCode::from_str("NPC_").unwrap()),
            ..Default::default()
        };
        let mut mapper = FormKeyMapper::new([], MapperOptions::default(), &mut mapper_interner);
        let ctx = FixupContext {
            source_handle_id: 1,
            target_handle_id: 2,
            schema_target: &schema,
            schema_source: &schema,
            skip_record_sigs: crate::fixups::empty_skip_record_sigs(),
            mod_path: None,
            source_extracted_dir: None,
            target_master_handle_ids: &[],
            config: &config,
        };
        assert!(StripCreatureSubgraphAdditiveRaceFixup.applies_to(&ctx));
        let _ = mapper;
    }
}
